title: Welcome to my blog
author: Enmanuel López
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog, I hope do you like it.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
